# Generated by Django 4.2.26 on 2026-01-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reserves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
